export interface IStudent{
    name:string;
    dob:any;
    email:string;
    mobile:number;
    gender:string;
    currentaddress:string;
    permanentaddress:string;
    sameaddress:boolean;
    state1:string;
    district1:string;
    roll:string;
    schoolname:string;
    studentmark:{
        subject:string;
        mark:string;
    }[];    
    agree:boolean;
    captcha:string;
    total:string;
    percentage:string;
    grade:string;
}